   classDiagram
   class Affidavit{
   +String VIDN
   +String firstName
   +String lastName
   +String streetAddress
   +String addressLine2
   +String city
   +String stateCode
   +String ZIP5
   +String DLN
   +String stateIDN
   +String dateOfBirth
   +String SSN
   +String email
   +String mobilePhone
   +Boolean eligibleAbsentee
   +Boolean disabilityAbsentee
   +Boolean UOCAVAAbsentee
   +Boolean DLPhotoRequired
   +String electionJurisdiction
   +Int precinctID
   +String partyAffiliation
   +Int ballotID
   +Int completedN
   +Int incompletedN
   +String completeTimeStamp
   +String incompletedTimeStamp
}
